<Project>
  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <CoverletOutput>$(MSBuildProjectDirectory)/TestResults/coverage/</CoverletOutput>
    <Threshold>90</Threshold>
    <ThresholdType>line</ThresholdType>
    <ThresholdStat>total</ThresholdStat>
    <ExcludeByFile>**/obj/**/*.cs;**/bin/**/*.cs;**/Migrations/**/*.cs;**/Properties/AssemblyInfo.cs</ExcludeByFile>
  </PropertyGroup>
</Project>
