<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <IsPackable>false</IsPackable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Ardalis.Specification" Version="9.3.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
        <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
    </ItemGroup>
</Project>
