<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>SharedLibrary.PostgreSql.Dapper</PackageId>
        <PackageVersion>$(Version)</PackageVersion>
        <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageOutputPath>../../../../nugets</PackageOutputPath>
        <IncludeReferencedProjects>true</IncludeReferencedProjects>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
        <PackageReference Include="Dapper" Version="2.1.72" />
        <PackageReference Include="Npgsql" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SharedLibrary.Dapper\SharedLibrary.Dapper.csproj">
            <PrivateAssets>all</PrivateAssets>
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
        </ProjectReference>
        <ProjectReference Include="..\SharedLibrary\SharedLibrary.csproj">
            <PrivateAssets>all</PrivateAssets>
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>
</Project>
