<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Version.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>SharedLibrary.PostgreSql.EntityFramework</PackageId>
        <PackageVersion>$(Version)</PackageVersion>
        <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageOutputPath>../../../../nugets</PackageOutputPath>
        <IncludeReferencedProjects>true</IncludeReferencedProjects>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SharedLibrary.EntityFramework\SharedLibrary.EntityFramework.csproj">
            <PrivateAssets>all</PrivateAssets>
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
        </ProjectReference>
        <ProjectReference Include="..\SharedLibrary\SharedLibrary.csproj">
            <PrivateAssets>all</PrivateAssets>
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>

</Project>
